name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  install-lint-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint the code
        run: npm run lint

      # - name: Analyze unused files and dependencies
      #   run: pnpm knip

      - name: Run Prettier check
        run: npm run format:check

      - name: Run unit tests
        run: npm run test:unit

      - name: Build the project
        run: npm run build

      - name: Install Playwright browser
        run: npx playwright install --with-deps chromium

      - name: Run browser UI tests
        run: npm run test:ui

      - name: Run service template checks
        shell: bash
        run: |
          bash ./scripts/test.sh
          bash ./scripts/package.sh
